### ISSUE TITLE
PuppetDB Dashboard not working with 1.11-RC2

### ISSUE THREAD

**Issue by mclueppers** [theforeman/puppetdb_foreman#21]
After upgrading to Foreman 1.11-RC2 my PuppetDB Dashboard stopped working. I can see the following error in the logs.

https://gist.github.com/mclueppers/26c4f9083902b92d79a4

**Comment by Conzar** [comment]
Its also not working in 1.11 stable.

**Comment by mmoll** [comment]
please test with 1.0.3 (right now building packages for the apt repo, yum should follow shortly)

**Comment by mclueppers** [comment]
Seems to be working now
