### ISSUE TITLE
PuppetDB URLS needs to be updated

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/puppetdb_foreman#24]
Hi Guys,

The following URLS needs to be updated in the docs:

**From:**

:puppetdb:
  :enabled: true
  :address: 'https://puppetdb:8081/v2/commands'
  :dashboard_address: 'http://puppetdb:8080/dashboard'

**To**

:puppetdb:
  :enabled: true
  :address: 'https://puppetdb:8081/pdb/cmd/v1' **<- Not sure about this**
  :dashboard_address: 'http://puppetdb:8080/pdb/dashboard'

**Comment by dLobatog** [comment]
@Yamakasi Already updated after the 2.0 publication
