### ISSUE TITLE
Does it work with puppetdb 4.2.2

### ISSUE THREAD

**Issue by amateo** [theforeman/puppetdb_foreman#25]
Hi,
I have installed in my foreman 1.13 server. After changing URLs, all I have in monitoring screen is ```PuppetDB (unknown version)```.
Is it supposed to work with puppetdb 4.2.2 server?

**Comment by kalinux** [comment]
Hi

Im not user of this repo but i have some info about what your asking , actually as you can see 
```
:puppetdb:
  :enabled: true
  :address: 'https://puppetdb:8081**/v2/**commands'
  :dashboard_address: 'http://puppetdb:8080/dashboard'
```
v2 means puppetdb version 2.x.x . I`m also searching way to hack this plugin to get it worked with puppetdb 4.x.x .
Sorry if im publishing some wrong information , 

Regards
Karen

**Comment by guimaluf** [comment]
You should change the `dashboard_address` to
```
:dashboard_address: 'http://puppetdb:8080/pdb/dashboard'
```

**Comment by dLobatog** [comment]
@amateo Please use version 2.0, it supports PuppetDB 4.x, it was released a few days ago. Check the README for the necessary info.

Thanks for opening this!
