### ISSUE TITLE
Gem dates are incorrect

### ISSUE THREAD

**Issue by domcleal** [theforeman/puppetdb_foreman#27]
The gem specification date in puppetdb_foreman.gemspec is hardcoded to 2015-10-25, it should use today's date (programmatically) or be updated on each release.

(see https://rubygems.org/gems/puppetdb_foreman/versions)

**Comment by timogoebel** [comment]
Fixed in 62aca1d7eea34cfb5e386754da0b0d674b5aa894, thanks @domcleal!
