### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by metalcated** [theforeman/puppetdb_foreman#69]
Is this still being maintained? And will there be support added for Foreman version 2+? Thanks

**Comment by timogoebel** [comment]
@metalcated: Does this imply, that this plugin does not work for Foreman 2.0 + ?

**Comment by metalcated** [comment]
I am not sure if it's a change on the Puppet end or if something needs to change here, but I did notice that the private key is unable to be read by this plugin and thus an error is thrown in the foreman UI "permission denied." One you set the permissions to something unsafe for a private key (644), the plugin works again and I no longer receive a permissions error.

**Comment by laugmanuel** [comment]
@metalcated , which path do you use for the private key? If you are using the default Puppet key dir (`/etc/puppetlabs/puppet/ssl/private_keys/`) this is just a limitation of file system permissions as Foreman is ran with the `foreman` user by default.

We use some custom Puppet code which copies the Puppet private key to a different location and sets the permissions and owner/group accordingly. Then we use this file for the plugin.

**Comment by timogoebel** [comment]
@metalcated: To answer your original question: Yes. This plugin is still being maintained.

**Comment by metalcated** [comment]
Yes this is the exact error: 

`Oops, we're sorry but something went wrong Permission denied @ rb_sysopen - /etc/puppetlabs/puppet/ssl/private_keys/fqdn.pem`

I did add the foreman user to the puppet group but didn't restart the services. That would be the gotcha. I will update shortly if that fixes my issue.

**Comment by metalcated** [comment]
Yep, that seemed to work. Thanks all.
